# Generated by Django 5.0.2 on 2024-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(max_length=255)),
                ('flight_details', models.CharField(max_length=255)),
                ('trip_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('num_passengers', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
