# Generated by Django 5.0.2 on 2024-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'manager'), ('agent', 'agent')], max_length=20, null=True),
        ),
    ]
