# Generated by Django 5.0.2 on 2024-03-26 06:13

import crmApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', crmApp.models.CustomUserManager()),
            ],
        ),
    ]
