# Generated by Django 5.0.2 on 2024-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
