# Generated by Django 5.0.2 on 2024-03-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_customuser_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
    ]
