# Generated by Django 5.0.2 on 2024-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_invoice_status_alter_booking_flight_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
