# Generated by Django 5.0.2 on 2024-03-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='acknowledgment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20),
        ),
    ]
