# Generated by Django 5.0.2 on 2024-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_booking_email_booking_phone_number_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', max_length=20)),
                ('activation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PNR_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=10)),
                ('ref_id', models.TextField(max_length=200)),
                ('address', models.TextField(default='', max_length=255)),
                ('zip', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_manipulation_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Price_manipulation_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
