# Generated by Django 5.0.2 on 2024-03-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_validity', to='crmApp.center')),
            ],
        ),
    ]
