# Generated by Django 5.0.2 on 2024-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_center_acknowledgment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='signed_at',
            field=models.DateTimeField(blank=True, default='Not signed yet', null=True),
        ),
    ]
