# Generated by Django 5.0.2 on 2024-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='validity',
            name='expiry_value',
            field=models.CharField(default='valid', max_length=20),
        ),
    ]
