# Generated by Django 5.0.2 on 2024-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_markupcontrol_pnr_table_price_manipulation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
