# Generated by Django 5.0.2 on 2024-03-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_booking_lead_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rejection_date',
            new_name='change_date',
        ),
    ]
