# Generated by Django 5.0.2 on 2024-03-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_signaturerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignatureRequest',
        ),
    ]
