# Generated by Django 5.0.2 on 2024-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_remove_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('agent', 'agent')], max_length=20),
        ),
    ]
