# Generated by Django 5.0.2 on 2024-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_center_signed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='signed_at',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00', null=True),
        ),
    ]
