# Generated by Django 5.0.2 on 2024-03-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_validity_expiry_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmApp.center')),
            ],
        ),
    ]
