# Generated by Django 5.0.2 on 2024-03-21 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_payment_delete_signaturerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(max_length=16, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1000000000000000)]),
        ),
    ]
