# Generated by Django 5.0.2 on 2024-03-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_refund_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
