# Generated by Django 5.0.2 on 2024-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='duration',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
