# Generated by Django 5.0.2 on 2024-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_alter_center_signed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='signed_at',
            field=models.CharField(blank=True, default='Not signed yet', max_length=20, null=True),
        ),
    ]
