# Generated by Django 5.0.2 on 2024-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_alter_payment_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
