# Generated by Django 5.0.2 on 2024-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_customuser_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_confirmation_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_passenger', models.IntegerField()),
                ('credit_card_no', models.CharField(max_length=20)),
                ('confirmation_mail_status', models.CharField(max_length=50)),
                ('chargeback_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=100)),
                ('chargeback_received_date', models.DateField()),
                ('chargeback_status', models.CharField(max_length=50)),
                ('chargeback_lead_status', models.CharField(max_length=50)),
            ],
        ),
    ]
