# Generated by Django 5.0.2 on 2024-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0006_chargeback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeback',
            name='chargeback_lead_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
