# Generated by Django 5.0.2 on 2024-03-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_booking_center'),
        ('crmApp', '0006_alter_center_signed_at'),
    ]

    operations = [
    ]
