# Generated by Django 5.0.2 on 2024-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User')], max_length=10),
        ),
    ]
