# Generated by Django 5.0.2 on 2024-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0007_merge_0005_booking_center_0006_alter_center_signed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='acknowledgment_status',
        ),
        migrations.RemoveField(
            model_name='center',
            name='signed_at',
        ),
        migrations.AddField(
            model_name='mco',
            name='acknowledgment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mco',
            name='signed_at',
            field=models.CharField(blank=True, default='Not signed yet', max_length=20, null=True),
        ),
    ]
