# Generated by Django 5.0.2 on 2024-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('agent', 'Agent')], max_length=10),
        ),
    ]
