# Generated by Django 5.0.2 on 2024-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0007_merge_0005_booking_center_0006_alter_center_signed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'manager'), ('agent', 'agent')], max_length=20, null=True),
        ),
    ]
