# Generated by Django 5.0.2 on 2024-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0007_apirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
