# Generated by Django 5.0.2 on 2024-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0007_alter_chargeback_chargeback_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeback',
            name='chargeback_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
