# Generated by Django 5.0.2 on 2024-03-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0008_apirequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auth',
            field=models.CharField(default='Not Authorized', max_length=20),
        ),
    ]
