# Generated by Django 5.0.2 on 2024-03-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0008_alter_chargeback_chargeback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeback',
            name='lead_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_bookings', to='crmApp.booking'),
        ),
    ]
