# Generated by Django 5.0.2 on 2024-03-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0009_chargeback_lead_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeback',
            old_name='lead_agent',
            new_name='Booking',
        ),
    ]
