# Generated by Django 5.0.2 on 2024-03-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0009_booking_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='markup_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_discount',
            field=models.FloatField(),
        ),
    ]
