# Generated by Django 5.0.2 on 2024-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0010_alter_invoice_base_price_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='markup_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
