# Generated by Django 5.0.2 on 2024-03-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0010_rename_lead_agent_chargeback_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeback',
            name='arrival_city',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='customer_phone_no',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='departure_city',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='no_of_passenger',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='price',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rejectedbooking',
            name='customer_name',
        ),
    ]
