# Generated by Django 5.0.2 on 2024-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0010_rejectedbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
