# Generated by Django 5.0.2 on 2024-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0011_remove_chargeback_arrival_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
