# Generated by Django 5.0.2 on 2024-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0011_booking_rejection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
