# Generated by Django 5.0.2 on 2024-03-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0013_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
