# Generated by Django 5.0.2 on 2024-03-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0016_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_description', models.CharField(max_length=100)),
                ('total_additional', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='additional_charges',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='additional_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_additional',
        ),
        migrations.AddField(
            model_name='invoice',
            name='charges',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crmApp.additionalcharge'),
            preserve_default=False,
        ),
    ]
