# Generated by Django 5.0.2 on 2024-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0017_additionalcharge_remove_invoice_additional_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='charges',
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_description',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_additional',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Additionalcharge',
        ),
    ]
