# Generated by Django 5.0.2 on 2024-03-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0019_additionalcharge_remove_invoice_additional_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcharge',
            name='total_additional',
        ),
    ]
