# Generated by Django 5.0.2 on 2024-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0020_remove_additionalcharge_total_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='additional_description',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
