# Generated by Django 5.0.2 on 2024-03-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0021_alter_additionalcharge_additional_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='charge',
        ),
        migrations.DeleteModel(
            name='AdditionalCharge',
        ),
    ]
