# Generated by Django 5.0.2 on 2024-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0022_remove_invoice_charge_delete_additionalcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
