# Generated by Django 5.0.2 on 2024-03-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0023_additioncharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='additioncharge',
            name='invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crmApp.invoice'),
        ),
    ]
