# Generated by Django 5.0.2 on 2024-03-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0026_invoice_invoice_id_alter_booking_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
