# Generated by Django 5.0.2 on 2024-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0026_invoice_invoice_id_alter_booking_lead_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
